### ISSUE TITLE
Incorrect format of double with with input 1.0

### ISSUE THREAD

**Issue by alsted** [carueda/tscfg#50]
When generating a java class from the following input:

my.parameter = 1.1
I get: 

public static class my {
   public final double parameter;
}

All is well, but:
my.parameter = 1.0
I get: 

public static class my {
   public final int parameter;
}

Which i think should be a double. The test in https://github.com/carueda/tscfg/blob/master/src/test/scala/tscfg/generators/java/JavaMainSpec.scala :

    "example 1" in {
      val c = new JavaIssue15bCfg(ConfigFactory.parseString(
        """
          |strings:  [hello, world, true]
          |integers: [[1, 2, 3], [4, 5]]
          |doubles:  [3.14, 2.7182, 1.618]
          |longs:    [1, 9999999999]
          |booleans: [true, false]
          |""".stripMargin
      ))

is missing e.g. 4.0 in doubles to test this case.

**Comment by carueda** [comment]
Thanks @alsted for your interest in tscfg and reporting this issue.

Please note this is actually a limitation caused by the use of the  Typesafe Config library itself for parsing the input for purposes of generating the wrapper.

In concrete, your input `parameter = 1.0` gets captured in the `Config` instance created by that library as `parameter = 1`. That is, the fact that it was a literal double is lost because it's effectively an integer (so tscfg ends up associating integer as the type of the parameter). This kind of makes sense from the point of view of Typesafe Config essentially because: i) it deals with concrete config input (as opposed to a schema as used in tscfg); ii) it complementary offers multiple ways to get the value of the particular parameter, including `getInt`, `getDouble`, etc., so, in other words, it defers to the user to decide how to access the value.  

So, strictly speaking this is a bug and I'm marking it as such.  A possible solution is to rely on a different parsing mechanism for processing the input for the wrapper generation.

**Workaround**: Simply make the type explicit, eg., `parameter = double | 1`.
(BTW, note that that's what's done in the JavaIssue15bCfg that you refer to above: the types are explicit so there's no problem even if adding 4.0 and similar valuesc to the doubles entry in the test.)

**Comment by alsted** [comment]
@carueda Thanks for the concise reply and work around.
